main: "net.telentity.Telentity"
name: "Telentity"
version: 0.2.6

# Telentity will function on all versions.
# Whether 3rd 'Preventors' function relies on the
# individual Preventors themselves.
api-version: "1.13"